version: '3.7'

services:
  fusionpbx:
    image: quay.io/spivegin/fusionpbx:latest
    volumes:
      - etc-fusionpbx:/etc/fusionpbx
      - etc-freeswitch:/etc/freeswitch
      - var-lib-freeswitch:/var/lib/freeswitch
      - usr-share-freeswitch:/usr/share/freeswitch
    ports:
      - "5060:5060/udp"
      - "5081:5081/udp"
    networks:
      rafflenet:
      fusion_main:
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - node.labels.fusion == true
  db:
      image: postgres:10-alpine
      environment:
        POSTGRES_DB: 'fusionpbx'
        POSTGRES_USER: 'fusionpbx'
        POSTGRES_PASSWORD: 'mODR8lu0lpDpAt5ukD5a'
      networks:
        fusion_main:
      deploy:
        placement:
          constraints:
            - node.labels.database == true          
volumes:
  fusionpbx:
  etc-fusionpbx:
  etc-freeswitch:
  var-lib-freeswitch:
  usr-share-freeswitch:
networks:
  fusion_main:
  rafflenet:
    external: true 